# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1389, 894)
        self.tabs = QtWidgets.QTabWidget(Dialog)
        self.tabs.setGeometry(QtCore.QRect(0, 0, 1391, 891))
        self.tabs.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.tabs.setObjectName("tabs")
        self.main_tab = QtWidgets.QWidget()
        self.main_tab.setObjectName("main_tab")
        self.pressure_view = QtWidgets.QGraphicsView(self.main_tab)
        self.pressure_view.setGeometry(QtCore.QRect(570, 90, 791, 551))
        self.pressure_view.setObjectName("pressure_view")
        self.label = QtWidgets.QLabel(self.main_tab)
        self.label.setGeometry(QtCore.QRect(580, 30, 121, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.main_tab)
        self.label_2.setGeometry(QtCore.QRect(970, 30, 121, 31))
        self.label_2.setObjectName("label_2")
        self.reset_button = QtWidgets.QPushButton(self.main_tab)
        self.reset_button.setGeometry(QtCore.QRect(130, 570, 191, 71))
        self.reset_button.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.reset_button.setObjectName("reset_button")
        self.auto_button = QtWidgets.QPushButton(self.main_tab)
        self.auto_button.setGeometry(QtCore.QRect(130, 670, 191, 71))
        self.auto_button.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.auto_button.setObjectName("auto_button")
        self.stop_button = QtWidgets.QPushButton(self.main_tab)
        self.stop_button.setGeometry(QtCore.QRect(130, 770, 191, 71))
        self.stop_button.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.stop_button.setObjectName("stop_button")
        self.label_3 = QtWidgets.QLabel(self.main_tab)
        self.label_3.setGeometry(QtCore.QRect(170, 460, 171, 21))
        self.label_3.setObjectName("label_3")
        self.dev_bar_code_browser = QtWidgets.QTextBrowser(self.main_tab)
        self.dev_bar_code_browser.setGeometry(QtCore.QRect(40, 490, 471, 51))
        self.dev_bar_code_browser.setObjectName("dev_bar_code_browser")
        self.label_4 = QtWidgets.QLabel(self.main_tab)
        self.label_4.setGeometry(QtCore.QRect(40, 160, 71, 31))
        self.label_4.setObjectName("label_4")
        self.status_label = QtWidgets.QLabel(self.main_tab)
        self.status_label.setGeometry(QtCore.QRect(140, 40, 161, 91))
        self.status_label.setObjectName("status_label")
        self.label_6 = QtWidgets.QLabel(self.main_tab)
        self.label_6.setGeometry(QtCore.QRect(20, 250, 91, 61))
        self.label_6.setObjectName("label_6")
        self.dev_info_browser = QtWidgets.QTextBrowser(self.main_tab)
        self.dev_info_browser.setGeometry(QtCore.QRect(120, 220, 411, 221))
        self.dev_info_browser.setObjectName("dev_info_browser")
        self.ip_line_edit = QtWidgets.QLineEdit(self.main_tab)
        self.ip_line_edit.setGeometry(QtCore.QRect(120, 150, 351, 51))
        self.ip_line_edit.setObjectName("ip_line_edit")
        self.connect_button = QtWidgets.QPushButton(self.main_tab)
        self.connect_button.setGeometry(QtCore.QRect(392, 77, 121, 41))
        self.connect_button.setObjectName("connect_button")
        self.current_pressure_lcd = QtWidgets.QLCDNumber(self.main_tab)
        self.current_pressure_lcd.setGeometry(QtCore.QRect(700, 20, 201, 51))
        self.current_pressure_lcd.setObjectName("current_pressure_lcd")
        self.max_pressure_lcd = QtWidgets.QLCDNumber(self.main_tab)
        self.max_pressure_lcd.setGeometry(QtCore.QRect(1090, 20, 201, 51))
        self.max_pressure_lcd.setObjectName("max_pressure_lcd")
        self.tabs.addTab(self.main_tab, "")
        self.io_tab = QtWidgets.QWidget()
        self.io_tab.setObjectName("io_tab")
        self.input_frame = QtWidgets.QFrame(self.io_tab)
        self.input_frame.setGeometry(QtCore.QRect(190, 160, 451, 501))
        self.input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_frame.setObjectName("input_frame")
        self.label_5 = QtWidgets.QLabel(self.input_frame)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 91, 31))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.input_frame)
        self.label_7.setGeometry(QtCore.QRect(30, 60, 55, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.input_frame)
        self.label_8.setGeometry(QtCore.QRect(30, 100, 55, 16))
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(self.input_frame)
        self.label_12.setGeometry(QtCore.QRect(90, 60, 241, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.input_frame)
        self.label_13.setGeometry(QtCore.QRect(90, 100, 241, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.input_frame)
        self.label_14.setGeometry(QtCore.QRect(90, 180, 241, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.input_frame)
        self.label_15.setGeometry(QtCore.QRect(30, 140, 55, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.input_frame)
        self.label_16.setGeometry(QtCore.QRect(30, 180, 55, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.input_frame)
        self.label_17.setGeometry(QtCore.QRect(90, 140, 241, 21))
        self.label_17.setObjectName("label_17")
        self.label_32 = QtWidgets.QLabel(self.input_frame)
        self.label_32.setGeometry(QtCore.QRect(90, 260, 241, 21))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.input_frame)
        self.label_33.setGeometry(QtCore.QRect(90, 220, 241, 21))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.input_frame)
        self.label_34.setGeometry(QtCore.QRect(90, 340, 241, 21))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.input_frame)
        self.label_35.setGeometry(QtCore.QRect(90, 300, 241, 21))
        self.label_35.setObjectName("label_35")
        self.label_9 = QtWidgets.QLabel(self.input_frame)
        self.label_9.setGeometry(QtCore.QRect(30, 260, 55, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.input_frame)
        self.label_10.setGeometry(QtCore.QRect(30, 220, 55, 16))
        self.label_10.setObjectName("label_10")
        self.label_36 = QtWidgets.QLabel(self.input_frame)
        self.label_36.setGeometry(QtCore.QRect(30, 300, 55, 16))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.input_frame)
        self.label_37.setGeometry(QtCore.QRect(30, 340, 55, 16))
        self.label_37.setObjectName("label_37")
        self.io_table_in_label_7 = QtWidgets.QLabel(self.input_frame)
        self.io_table_in_label_7.setGeometry(QtCore.QRect(180, 340, 55, 16))
        self.io_table_in_label_7.setStyleSheet("QLabel {background-color: black}")
        self.io_table_in_label_7.setText("")
        self.io_table_in_label_7.setObjectName("io_table_in_label_7")
        self.io_table_in_label_6 = QtWidgets.QLabel(self.input_frame)
        self.io_table_in_label_6.setGeometry(QtCore.QRect(180, 300, 55, 16))
        self.io_table_in_label_6.setStyleSheet("QLabel {background-color: black}")
        self.io_table_in_label_6.setText("")
        self.io_table_in_label_6.setObjectName("io_table_in_label_6")
        self.io_table_in_label_5 = QtWidgets.QLabel(self.input_frame)
        self.io_table_in_label_5.setGeometry(QtCore.QRect(180, 260, 55, 16))
        self.io_table_in_label_5.setStyleSheet("QLabel {background-color: black}")
        self.io_table_in_label_5.setText("")
        self.io_table_in_label_5.setObjectName("io_table_in_label_5")
        self.io_table_in_label_4 = QtWidgets.QLabel(self.input_frame)
        self.io_table_in_label_4.setGeometry(QtCore.QRect(180, 220, 55, 16))
        self.io_table_in_label_4.setStyleSheet("QLabel {background-color: black}")
        self.io_table_in_label_4.setText("")
        self.io_table_in_label_4.setObjectName("io_table_in_label_4")
        self.io_table_in_label_0 = QtWidgets.QLabel(self.input_frame)
        self.io_table_in_label_0.setGeometry(QtCore.QRect(180, 60, 55, 16))
        self.io_table_in_label_0.setStyleSheet("QLabel {background-color: black}")
        self.io_table_in_label_0.setText("")
        self.io_table_in_label_0.setObjectName("io_table_in_label_0")
        self.io_table_in_label_2 = QtWidgets.QLabel(self.input_frame)
        self.io_table_in_label_2.setGeometry(QtCore.QRect(180, 140, 55, 16))
        self.io_table_in_label_2.setStyleSheet("QLabel {background-color: black}")
        self.io_table_in_label_2.setText("")
        self.io_table_in_label_2.setObjectName("io_table_in_label_2")
        self.io_table_in_label_3 = QtWidgets.QLabel(self.input_frame)
        self.io_table_in_label_3.setGeometry(QtCore.QRect(180, 180, 55, 16))
        self.io_table_in_label_3.setStyleSheet("QLabel {background-color: black}")
        self.io_table_in_label_3.setText("")
        self.io_table_in_label_3.setObjectName("io_table_in_label_3")
        self.io_table_in_label_1 = QtWidgets.QLabel(self.input_frame)
        self.io_table_in_label_1.setGeometry(QtCore.QRect(180, 100, 55, 16))
        self.io_table_in_label_1.setStyleSheet("QLabel {background-color: black}")
        self.io_table_in_label_1.setText("")
        self.io_table_in_label_1.setObjectName("io_table_in_label_1")
        self.input_frame_2 = QtWidgets.QFrame(self.io_tab)
        self.input_frame_2.setGeometry(QtCore.QRect(660, 160, 451, 501))
        self.input_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_frame_2.setObjectName("input_frame_2")
        self.label_18 = QtWidgets.QLabel(self.input_frame_2)
        self.label_18.setGeometry(QtCore.QRect(20, 10, 91, 31))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.input_frame_2)
        self.label_19.setGeometry(QtCore.QRect(30, 60, 55, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.input_frame_2)
        self.label_20.setGeometry(QtCore.QRect(30, 100, 55, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.input_frame_2)
        self.label_21.setGeometry(QtCore.QRect(90, 60, 241, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.input_frame_2)
        self.label_22.setGeometry(QtCore.QRect(90, 100, 241, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.input_frame_2)
        self.label_23.setGeometry(QtCore.QRect(90, 180, 241, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.input_frame_2)
        self.label_24.setGeometry(QtCore.QRect(30, 140, 55, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.input_frame_2)
        self.label_25.setGeometry(QtCore.QRect(30, 180, 55, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.input_frame_2)
        self.label_26.setGeometry(QtCore.QRect(90, 140, 241, 21))
        self.label_26.setObjectName("label_26")
        self.io_table_out_button_0 = QtWidgets.QPushButton(self.input_frame_2)
        self.io_table_out_button_0.setGeometry(QtCore.QRect(330, 50, 41, 28))
        self.io_table_out_button_0.setText("")
        self.io_table_out_button_0.setObjectName("io_table_out_button_0")
        self.io_table_out_button_1 = QtWidgets.QPushButton(self.input_frame_2)
        self.io_table_out_button_1.setGeometry(QtCore.QRect(330, 90, 41, 28))
        self.io_table_out_button_1.setText("")
        self.io_table_out_button_1.setObjectName("io_table_out_button_1")
        self.io_table_out_button_2 = QtWidgets.QPushButton(self.input_frame_2)
        self.io_table_out_button_2.setGeometry(QtCore.QRect(330, 130, 41, 28))
        self.io_table_out_button_2.setText("")
        self.io_table_out_button_2.setObjectName("io_table_out_button_2")
        self.io_table_out_button_3 = QtWidgets.QPushButton(self.input_frame_2)
        self.io_table_out_button_3.setGeometry(QtCore.QRect(330, 170, 41, 28))
        self.io_table_out_button_3.setText("")
        self.io_table_out_button_3.setObjectName("io_table_out_button_3")
        self.io_table_out_label_3 = QtWidgets.QLabel(self.input_frame_2)
        self.io_table_out_label_3.setGeometry(QtCore.QRect(240, 180, 55, 16))
        self.io_table_out_label_3.setStyleSheet("QLabel {background-color: black}")
        self.io_table_out_label_3.setText("")
        self.io_table_out_label_3.setObjectName("io_table_out_label_3")
        self.io_table_out_label_1 = QtWidgets.QLabel(self.input_frame_2)
        self.io_table_out_label_1.setGeometry(QtCore.QRect(240, 100, 55, 16))
        self.io_table_out_label_1.setStyleSheet("QLabel {background-color: black}")
        self.io_table_out_label_1.setText("")
        self.io_table_out_label_1.setObjectName("io_table_out_label_1")
        self.io_table_out_label_0 = QtWidgets.QLabel(self.input_frame_2)
        self.io_table_out_label_0.setGeometry(QtCore.QRect(240, 60, 55, 16))
        self.io_table_out_label_0.setStyleSheet("QLabel {background-color: black}")
        self.io_table_out_label_0.setText("")
        self.io_table_out_label_0.setObjectName("io_table_out_label_0")
        self.io_table_out_label_2 = QtWidgets.QLabel(self.input_frame_2)
        self.io_table_out_label_2.setGeometry(QtCore.QRect(240, 140, 55, 16))
        self.io_table_out_label_2.setStyleSheet("QLabel {background-color: black}")
        self.io_table_out_label_2.setText("")
        self.io_table_out_label_2.setObjectName("io_table_out_label_2")
        self.label_54 = QtWidgets.QLabel(self.input_frame_2)
        self.label_54.setGeometry(QtCore.QRect(30, 340, 55, 16))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.input_frame_2)
        self.label_55.setGeometry(QtCore.QRect(90, 220, 241, 21))
        self.label_55.setObjectName("label_55")
        self.io_table_out_button_6 = QtWidgets.QPushButton(self.input_frame_2)
        self.io_table_out_button_6.setGeometry(QtCore.QRect(330, 290, 41, 28))
        self.io_table_out_button_6.setText("")
        self.io_table_out_button_6.setObjectName("io_table_out_button_6")
        self.label_56 = QtWidgets.QLabel(self.input_frame_2)
        self.label_56.setGeometry(QtCore.QRect(90, 340, 241, 21))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.input_frame_2)
        self.label_57.setGeometry(QtCore.QRect(30, 220, 55, 16))
        self.label_57.setObjectName("label_57")
        self.io_table_out_label_5 = QtWidgets.QLabel(self.input_frame_2)
        self.io_table_out_label_5.setGeometry(QtCore.QRect(240, 260, 55, 16))
        self.io_table_out_label_5.setStyleSheet("QLabel {background-color: black}")
        self.io_table_out_label_5.setText("")
        self.io_table_out_label_5.setObjectName("io_table_out_label_5")
        self.io_table_out_label_7 = QtWidgets.QLabel(self.input_frame_2)
        self.io_table_out_label_7.setGeometry(QtCore.QRect(240, 340, 55, 16))
        self.io_table_out_label_7.setStyleSheet("QLabel {background-color: black}")
        self.io_table_out_label_7.setText("")
        self.io_table_out_label_7.setObjectName("io_table_out_label_7")
        self.io_table_out_label_4 = QtWidgets.QLabel(self.input_frame_2)
        self.io_table_out_label_4.setGeometry(QtCore.QRect(240, 220, 55, 16))
        self.io_table_out_label_4.setStyleSheet("QLabel {background-color: black}")
        self.io_table_out_label_4.setText("")
        self.io_table_out_label_4.setObjectName("io_table_out_label_4")
        self.io_table_out_button_4 = QtWidgets.QPushButton(self.input_frame_2)
        self.io_table_out_button_4.setGeometry(QtCore.QRect(330, 210, 41, 28))
        self.io_table_out_button_4.setText("")
        self.io_table_out_button_4.setObjectName("io_table_out_button_4")
        self.io_table_out_label_6 = QtWidgets.QLabel(self.input_frame_2)
        self.io_table_out_label_6.setGeometry(QtCore.QRect(240, 300, 55, 16))
        self.io_table_out_label_6.setStyleSheet("QLabel {background-color: black}")
        self.io_table_out_label_6.setText("")
        self.io_table_out_label_6.setObjectName("io_table_out_label_6")
        self.label_63 = QtWidgets.QLabel(self.input_frame_2)
        self.label_63.setGeometry(QtCore.QRect(30, 260, 55, 16))
        self.label_63.setObjectName("label_63")
        self.io_table_out_button_5 = QtWidgets.QPushButton(self.input_frame_2)
        self.io_table_out_button_5.setGeometry(QtCore.QRect(330, 250, 41, 28))
        self.io_table_out_button_5.setText("")
        self.io_table_out_button_5.setObjectName("io_table_out_button_5")
        self.label_64 = QtWidgets.QLabel(self.input_frame_2)
        self.label_64.setGeometry(QtCore.QRect(30, 300, 55, 16))
        self.label_64.setObjectName("label_64")
        self.io_table_out_button_7 = QtWidgets.QPushButton(self.input_frame_2)
        self.io_table_out_button_7.setGeometry(QtCore.QRect(330, 330, 41, 28))
        self.io_table_out_button_7.setText("")
        self.io_table_out_button_7.setObjectName("io_table_out_button_7")
        self.label_65 = QtWidgets.QLabel(self.input_frame_2)
        self.label_65.setGeometry(QtCore.QRect(90, 260, 241, 21))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.input_frame_2)
        self.label_66.setGeometry(QtCore.QRect(90, 300, 241, 21))
        self.label_66.setObjectName("label_66")
        self.label_66.raise_()
        self.label_65.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.io_table_out_button_0.raise_()
        self.io_table_out_button_1.raise_()
        self.io_table_out_button_2.raise_()
        self.io_table_out_button_3.raise_()
        self.io_table_out_label_3.raise_()
        self.io_table_out_label_1.raise_()
        self.io_table_out_label_0.raise_()
        self.io_table_out_label_2.raise_()
        self.label_54.raise_()
        self.label_55.raise_()
        self.io_table_out_button_6.raise_()
        self.label_56.raise_()
        self.label_57.raise_()
        self.io_table_out_label_5.raise_()
        self.io_table_out_label_7.raise_()
        self.io_table_out_label_4.raise_()
        self.io_table_out_button_4.raise_()
        self.io_table_out_label_6.raise_()
        self.label_63.raise_()
        self.io_table_out_button_5.raise_()
        self.label_64.raise_()
        self.io_table_out_button_7.raise_()
        self.tabs.addTab(self.io_tab, "")
        self.set_tab = QtWidgets.QWidget()
        self.set_tab.setObjectName("set_tab")
        self.frame = QtWidgets.QFrame(self.set_tab)
        self.frame.setGeometry(QtCore.QRect(130, 90, 871, 671))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(40, 30, 111, 51))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame)
        self.label_28.setGeometry(QtCore.QRect(120, 110, 81, 41))
        self.label_28.setObjectName("label_28")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(220, 120, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.frame_2 = QtWidgets.QFrame(self.set_tab)
        self.frame_2.setGeometry(QtCore.QRect(1020, 50, 351, 321))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_29 = QtWidgets.QLabel(self.frame_2)
        self.label_29.setGeometry(QtCore.QRect(20, 20, 101, 31))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_2)
        self.label_30.setGeometry(QtCore.QRect(50, 70, 61, 31))
        self.label_30.setObjectName("label_30")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 120, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(190, 70, 93, 28))
        self.pushButton_5.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_31 = QtWidgets.QLabel(self.frame_2)
        self.label_31.setGeometry(QtCore.QRect(210, 120, 71, 21))
        self.label_31.setObjectName("label_31")
        self.tabs.addTab(self.set_tab, "")
        self.network_tab = QtWidgets.QWidget()
        self.network_tab.setObjectName("network_tab")
        self.label_58 = QtWidgets.QLabel(self.network_tab)
        self.label_58.setGeometry(QtCore.QRect(610, 310, 101, 31))
        self.label_58.setObjectName("label_58")
        self.local_ip_edit = QtWidgets.QLineEdit(self.network_tab)
        self.local_ip_edit.setGeometry(QtCore.QRect(720, 300, 351, 51))
        self.local_ip_edit.setObjectName("local_ip_edit")
        self.label_59 = QtWidgets.QLabel(self.network_tab)
        self.label_59.setGeometry(QtCore.QRect(380, 460, 101, 31))
        self.label_59.setObjectName("label_59")
        self.code_scannner_ip_edit = QtWidgets.QLineEdit(self.network_tab)
        self.code_scannner_ip_edit.setGeometry(QtCore.QRect(490, 450, 351, 51))
        self.code_scannner_ip_edit.setObjectName("code_scannner_ip_edit")
        self.plc_ip_edit = QtWidgets.QLineEdit(self.network_tab)
        self.plc_ip_edit.setGeometry(QtCore.QRect(390, 140, 351, 51))
        self.plc_ip_edit.setObjectName("plc_ip_edit")
        self.label_60 = QtWidgets.QLabel(self.network_tab)
        self.label_60.setGeometry(QtCore.QRect(280, 150, 101, 31))
        self.label_60.setObjectName("label_60")
        self.bc_receive_port_edit = QtWidgets.QLineEdit(self.network_tab)
        self.bc_receive_port_edit.setGeometry(QtCore.QRect(1070, 480, 351, 51))
        self.bc_receive_port_edit.setObjectName("bc_receive_port_edit")
        self.label_61 = QtWidgets.QLabel(self.network_tab)
        self.label_61.setGeometry(QtCore.QRect(960, 490, 101, 31))
        self.label_61.setObjectName("label_61")
        self.plc_port_edit = QtWidgets.QLineEdit(self.network_tab)
        self.plc_port_edit.setGeometry(QtCore.QRect(900, 170, 351, 51))
        self.plc_port_edit.setObjectName("plc_port_edit")
        self.label_62 = QtWidgets.QLabel(self.network_tab)
        self.label_62.setGeometry(QtCore.QRect(790, 180, 101, 31))
        self.label_62.setObjectName("label_62")
        self.tabs.addTab(self.network_tab, "")

        self.retranslateUi(Dialog)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#ff5500;\">当前负压</span><span style=\" font-size:11pt; font-weight:600; color:#ff5500; vertical-align:sub;\">(Kpa)</span><span style=\" font-size:11pt; font-weight:600; color:#ff5500;\">:</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#ff5500;\">最大负压</span><span style=\" font-size:11pt; font-weight:600; color:#ff5500; vertical-align:sub;\">(Kpa)</span><span style=\" font-size:11pt; font-weight:600; color:#ff5500;\">:</span></p></body></html>"))
        self.reset_button.setText(_translate("Dialog", "复位"))
        self.auto_button.setText(_translate("Dialog", "自动"))
        self.stop_button.setText(_translate("Dialog", "停止"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">当前条形码</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">IP地址</span></p></body></html>"))
        self.status_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:48pt; font-weight:600; color:#00ff00;\">OK</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">设备信息</span></p></body></html>"))
        self.connect_button.setText(_translate("Dialog", "连接"))
        self.tabs.setTabText(self.tabs.indexOf(self.main_tab), _translate("Dialog", "主界面"))
        self.label_5.setText(_translate("Dialog", "输入"))
        self.label_7.setText(_translate("Dialog", "00.00"))
        self.label_8.setText(_translate("Dialog", "00.01"))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p>启动</p></body></html>"))
        self.label_13.setText(_translate("Dialog", "急停"))
        self.label_14.setText(_translate("Dialog", "光栅"))
        self.label_15.setText(_translate("Dialog", "00.02"))
        self.label_16.setText(_translate("Dialog", "00.03"))
        self.label_17.setText(_translate("Dialog", "热过载"))
        self.label_32.setText(_translate("Dialog", "备用"))
        self.label_33.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">备用</span></p></body></html>"))
        self.label_34.setText(_translate("Dialog", "备用"))
        self.label_35.setText(_translate("Dialog", "备用"))
        self.label_9.setText(_translate("Dialog", "00.05"))
        self.label_10.setText(_translate("Dialog", "00.04"))
        self.label_36.setText(_translate("Dialog", "00.06"))
        self.label_37.setText(_translate("Dialog", "00.07"))
        self.label_18.setText(_translate("Dialog", "输出"))
        self.label_19.setText(_translate("Dialog", "100.00"))
        self.label_20.setText(_translate("Dialog", "100.01"))
        self.label_21.setText(_translate("Dialog", "真空泵"))
        self.label_22.setText(_translate("Dialog", "下压缸"))
        self.label_23.setText(_translate("Dialog", "阀2（慢速阀）"))
        self.label_24.setText(_translate("Dialog", "100.02"))
        self.label_25.setText(_translate("Dialog", "100.03"))
        self.label_26.setText(_translate("Dialog", "阀1（快速阀）"))
        self.label_54.setText(_translate("Dialog", "100.07"))
        self.label_55.setText(_translate("Dialog", "阀3（排气阀）"))
        self.label_56.setText(_translate("Dialog", "蜂鸣器"))
        self.label_57.setText(_translate("Dialog", "100.04"))
        self.label_63.setText(_translate("Dialog", "100.05"))
        self.label_64.setText(_translate("Dialog", "100.06"))
        self.label_65.setText(_translate("Dialog", "OK"))
        self.label_66.setText(_translate("Dialog", "NG"))
        self.tabs.setTabText(self.tabs.indexOf(self.io_tab), _translate("Dialog", "输入/输出"))
        self.label_27.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">设定</span></p></body></html>"))
        self.label_28.setText(_translate("Dialog", "压力系数"))
        self.lineEdit.setText(_translate("Dialog", "0"))
        self.label_29.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">负压标定</span></p></body></html>"))
        self.label_30.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">负压1</span></p></body></html>"))
        self.pushButton_5.setText(_translate("Dialog", "获取"))
        self.label_31.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">0.000</span></p></body></html>"))
        self.tabs.setTabText(self.tabs.indexOf(self.set_tab), _translate("Dialog", "参数设定"))
        self.label_58.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">本机地址</span></p></body></html>"))
        self.local_ip_edit.setText(_translate("Dialog", "localhost"))
        self.label_59.setText(_translate("Dialog", "<html><head/><body><p>扫码枪地址</p></body></html>"))
        self.code_scannner_ip_edit.setText(_translate("Dialog", "localhost"))
        self.plc_ip_edit.setText(_translate("Dialog", "192.168.0.10"))
        self.label_60.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">PLC地址</span></p></body></html>"))
        self.bc_receive_port_edit.setText(_translate("Dialog", "12346"))
        self.label_61.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">本机端口</span></p></body></html>"))
        self.plc_port_edit.setText(_translate("Dialog", "9600"))
        self.label_62.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">PLC端口</span></p></body></html>"))
        self.tabs.setTabText(self.tabs.indexOf(self.network_tab), _translate("Dialog", "网络设定"))

