# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1389, 894)
        self.tabs = QtWidgets.QTabWidget(Dialog)
        self.tabs.setGeometry(QtCore.QRect(0, 0, 1391, 891))
        self.tabs.setObjectName("tabs")
        self.main_tab = QtWidgets.QWidget()
        self.main_tab.setObjectName("main_tab")
        self.pressure_view = QtWidgets.QGraphicsView(self.main_tab)
        self.pressure_view.setGeometry(QtCore.QRect(570, 90, 791, 551))
        self.pressure_view.setObjectName("pressure_view")
        self.label = QtWidgets.QLabel(self.main_tab)
        self.label.setGeometry(QtCore.QRect(580, 30, 121, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.main_tab)
        self.label_2.setGeometry(QtCore.QRect(970, 30, 121, 31))
        self.label_2.setObjectName("label_2")
        self.reset_button = QtWidgets.QPushButton(self.main_tab)
        self.reset_button.setGeometry(QtCore.QRect(130, 570, 191, 71))
        self.reset_button.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.reset_button.setObjectName("reset_button")
        self.auto_button = QtWidgets.QPushButton(self.main_tab)
        self.auto_button.setGeometry(QtCore.QRect(130, 670, 191, 71))
        self.auto_button.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.auto_button.setObjectName("auto_button")
        self.stop_button = QtWidgets.QPushButton(self.main_tab)
        self.stop_button.setGeometry(QtCore.QRect(130, 770, 191, 71))
        self.stop_button.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.stop_button.setObjectName("stop_button")
        self.label_3 = QtWidgets.QLabel(self.main_tab)
        self.label_3.setGeometry(QtCore.QRect(170, 460, 171, 21))
        self.label_3.setObjectName("label_3")
        self.dev_bar_code_browser = QtWidgets.QTextBrowser(self.main_tab)
        self.dev_bar_code_browser.setGeometry(QtCore.QRect(40, 490, 471, 51))
        self.dev_bar_code_browser.setObjectName("dev_bar_code_browser")
        self.label_4 = QtWidgets.QLabel(self.main_tab)
        self.label_4.setGeometry(QtCore.QRect(40, 160, 71, 31))
        self.label_4.setObjectName("label_4")
        self.status_label = QtWidgets.QLabel(self.main_tab)
        self.status_label.setGeometry(QtCore.QRect(140, 40, 161, 91))
        self.status_label.setObjectName("status_label")
        self.label_6 = QtWidgets.QLabel(self.main_tab)
        self.label_6.setGeometry(QtCore.QRect(20, 250, 91, 61))
        self.label_6.setObjectName("label_6")
        self.dev_info_browser = QtWidgets.QTextBrowser(self.main_tab)
        self.dev_info_browser.setGeometry(QtCore.QRect(120, 220, 411, 221))
        self.dev_info_browser.setObjectName("dev_info_browser")
        self.ip_line_edit = QtWidgets.QLineEdit(self.main_tab)
        self.ip_line_edit.setGeometry(QtCore.QRect(120, 150, 351, 51))
        self.ip_line_edit.setObjectName("ip_line_edit")
        self.connect_button = QtWidgets.QPushButton(self.main_tab)
        self.connect_button.setGeometry(QtCore.QRect(392, 77, 121, 41))
        self.connect_button.setObjectName("connect_button")
        self.current_pressure_lcd = QtWidgets.QLCDNumber(self.main_tab)
        self.current_pressure_lcd.setGeometry(QtCore.QRect(700, 20, 201, 51))
        self.current_pressure_lcd.setObjectName("current_pressure_lcd")
        self.max_pressure_lcd = QtWidgets.QLCDNumber(self.main_tab)
        self.max_pressure_lcd.setGeometry(QtCore.QRect(1090, 20, 201, 51))
        self.max_pressure_lcd.setObjectName("max_pressure_lcd")
        self.tabs.addTab(self.main_tab, "")
        self.io_tab = QtWidgets.QWidget()
        self.io_tab.setObjectName("io_tab")
        self.input_frame = QtWidgets.QFrame(self.io_tab)
        self.input_frame.setGeometry(QtCore.QRect(190, 160, 451, 501))
        self.input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_frame.setObjectName("input_frame")
        self.label_5 = QtWidgets.QLabel(self.input_frame)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 91, 31))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.input_frame)
        self.label_7.setGeometry(QtCore.QRect(30, 60, 55, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.input_frame)
        self.label_8.setGeometry(QtCore.QRect(30, 100, 55, 16))
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(self.input_frame)
        self.label_12.setGeometry(QtCore.QRect(90, 60, 241, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.input_frame)
        self.label_13.setGeometry(QtCore.QRect(90, 100, 241, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.input_frame)
        self.label_14.setGeometry(QtCore.QRect(90, 180, 241, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.input_frame)
        self.label_15.setGeometry(QtCore.QRect(30, 140, 55, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.input_frame)
        self.label_16.setGeometry(QtCore.QRect(30, 180, 55, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.input_frame)
        self.label_17.setGeometry(QtCore.QRect(90, 140, 241, 21))
        self.label_17.setObjectName("label_17")
        self.input_frame_2 = QtWidgets.QFrame(self.io_tab)
        self.input_frame_2.setGeometry(QtCore.QRect(720, 160, 451, 501))
        self.input_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_frame_2.setObjectName("input_frame_2")
        self.label_18 = QtWidgets.QLabel(self.input_frame_2)
        self.label_18.setGeometry(QtCore.QRect(20, 10, 91, 31))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.input_frame_2)
        self.label_19.setGeometry(QtCore.QRect(30, 60, 55, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.input_frame_2)
        self.label_20.setGeometry(QtCore.QRect(30, 100, 55, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.input_frame_2)
        self.label_21.setGeometry(QtCore.QRect(90, 60, 241, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.input_frame_2)
        self.label_22.setGeometry(QtCore.QRect(90, 100, 241, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.input_frame_2)
        self.label_23.setGeometry(QtCore.QRect(90, 180, 241, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.input_frame_2)
        self.label_24.setGeometry(QtCore.QRect(30, 140, 55, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.input_frame_2)
        self.label_25.setGeometry(QtCore.QRect(30, 180, 55, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.input_frame_2)
        self.label_26.setGeometry(QtCore.QRect(90, 140, 241, 21))
        self.label_26.setObjectName("label_26")
        self.pushButton = QtWidgets.QPushButton(self.input_frame_2)
        self.pushButton.setGeometry(QtCore.QRect(260, 60, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.input_frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 100, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.input_frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 140, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.input_frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(260, 180, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabs.addTab(self.io_tab, "")
        self.set_tab = QtWidgets.QWidget()
        self.set_tab.setObjectName("set_tab")
        self.frame = QtWidgets.QFrame(self.set_tab)
        self.frame.setGeometry(QtCore.QRect(130, 90, 871, 671))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(40, 30, 111, 51))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame)
        self.label_28.setGeometry(QtCore.QRect(120, 110, 81, 41))
        self.label_28.setObjectName("label_28")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(220, 120, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.frame_2 = QtWidgets.QFrame(self.set_tab)
        self.frame_2.setGeometry(QtCore.QRect(1020, 50, 351, 321))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_29 = QtWidgets.QLabel(self.frame_2)
        self.label_29.setGeometry(QtCore.QRect(20, 20, 101, 31))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_2)
        self.label_30.setGeometry(QtCore.QRect(50, 70, 61, 31))
        self.label_30.setObjectName("label_30")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 120, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(190, 70, 93, 28))
        self.pushButton_5.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_31 = QtWidgets.QLabel(self.frame_2)
        self.label_31.setGeometry(QtCore.QRect(210, 120, 71, 21))
        self.label_31.setObjectName("label_31")
        self.tabs.addTab(self.set_tab, "")

        self.retranslateUi(Dialog)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#ff5500;\">当前负压</span><span style=\" font-size:11pt; font-weight:600; color:#ff5500; vertical-align:sub;\">(Kpa)</span><span style=\" font-size:11pt; font-weight:600; color:#ff5500;\">:</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#ff5500;\">最大负压</span><span style=\" font-size:11pt; font-weight:600; color:#ff5500; vertical-align:sub;\">(Kpa)</span><span style=\" font-size:11pt; font-weight:600; color:#ff5500;\">:</span></p></body></html>"))
        self.reset_button.setText(_translate("Dialog", "复位"))
        self.auto_button.setText(_translate("Dialog", "自动"))
        self.stop_button.setText(_translate("Dialog", "停止"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">当前条形码</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">IP地址</span></p></body></html>"))
        self.status_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:48pt; font-weight:600; color:#00ff00;\">OK</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">设备信息</span></p></body></html>"))
        self.connect_button.setText(_translate("Dialog", "连接"))
        self.tabs.setTabText(self.tabs.indexOf(self.main_tab), _translate("Dialog", "主界面"))
        self.label_5.setText(_translate("Dialog", "输入 DI0-DI15"))
        self.label_7.setText(_translate("Dialog", "DI-00"))
        self.label_8.setText(_translate("Dialog", "DI-01"))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">备用</span></p></body></html>"))
        self.label_13.setText(_translate("Dialog", "备用"))
        self.label_14.setText(_translate("Dialog", "备用"))
        self.label_15.setText(_translate("Dialog", "DI-00"))
        self.label_16.setText(_translate("Dialog", "DI-01"))
        self.label_17.setText(_translate("Dialog", "备用"))
        self.label_18.setText(_translate("Dialog", "输入 DO0-DO15"))
        self.label_19.setText(_translate("Dialog", "DI-00"))
        self.label_20.setText(_translate("Dialog", "DI-01"))
        self.label_21.setText(_translate("Dialog", "备用"))
        self.label_22.setText(_translate("Dialog", "备用"))
        self.label_23.setText(_translate("Dialog", "备用"))
        self.label_24.setText(_translate("Dialog", "DI-00"))
        self.label_25.setText(_translate("Dialog", "DI-01"))
        self.label_26.setText(_translate("Dialog", "备用"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
        self.pushButton_2.setText(_translate("Dialog", "PushButton"))
        self.pushButton_3.setText(_translate("Dialog", "PushButton"))
        self.pushButton_4.setText(_translate("Dialog", "PushButton"))
        self.tabs.setTabText(self.tabs.indexOf(self.io_tab), _translate("Dialog", "输入/输出"))
        self.label_27.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">设定</span></p></body></html>"))
        self.label_28.setText(_translate("Dialog", "压力系数"))
        self.lineEdit.setText(_translate("Dialog", "0"))
        self.label_29.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">负压标定</span></p></body></html>"))
        self.label_30.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">负压1</span></p></body></html>"))
        self.pushButton_5.setText(_translate("Dialog", "获取"))
        self.label_31.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">0.000</span></p></body></html>"))
        self.tabs.setTabText(self.tabs.indexOf(self.set_tab), _translate("Dialog", "参数设定"))

